# https://megalinter.io/latest/descriptors/go_golangci_lint/
# https://github.com/oxsecurity/megalinter/blob/main/TEMPLATES/.golangci.yml
---
version: "2"

linters:
  enable:
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  gocritic:
    disabled-checks:
      - exitAfterDefer
  staticcheck:    
    checks:
      - all
      - "-SA1019"
