# https://megalinter.io/latest/descriptors/go_golangci_lint/  
# https://github.com/oxsecurity/megalinter/blob/main/TEMPLATES/.golangci.yml
---
run:
  timeout: 10m
  # Skip dirs that cause issues
  skip-dirs:
    - vendor

linters:
  enable:
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - unused
  disable:
    - typecheck

linters-settings:
  gocritic:
    disabled-checks:
      - exitAfterDefer
